# Data Accessing and overview

In this notebook i will be going thorugh dataset (Stack_Overflow_2025) and will be performing different pandas operations 
in order to have a good idea about rows,column,data inside this dataset.

I am doing this process in different layers - 
1. Layer 1 (Initial data inspection): Is to load dataset in and manually look through dataset as a glance over it to get what type of values there are in dataset.
2. Layer 2 (Data profiling): Is to perform some pandas operations to know about dataset in more deapth by knowing about columns and their info. 
3. Layer 3 (Data wrangling, Exploratory Visualization & Anomaly Detection): It is the layer in which i will be using some graph libraries with combination of advanced operations to gather intel on abnormalities and inconsistencies in data. I will be then fixing those with the help of other pandas tools. 

After those processes i will be filtering out columns and data which are necessary and essential for my analysis. 
(Final data selection)

### >>> Layer 1 
* Load the dataset
* head(), tail()
* Random samples with sample()
* shape
* Inspect columns
* Manually examine actual values
* Understand what kind of information each column contains

In [1]:
# Importing all necessary libs - 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dataset = pd.read_csv(r"C:\Users\afora\Desktop\Projects\Project_EDA\Data\stackoverflow_survey_2025.txt")

C:\Users\afora\AppData\Local\Temp\ipykernel_9332\2228508334.py:1: DtypeWarning: Columns (56: JobSatPoints_15_TEXT, 74: DatabaseHaveEntry, 92: DevEnvHaveEntry, 97: SOTagsHaveEntry, 98: SOTagsWant Entry, 105: OfficeStackWantEntry, 109: CommPlatformHaveEntr, 110: CommPlatformWantEntr, 132: SO_Actions_15_TEXT, 162: AIAgentOrchestration, 165: AIAgentObsWrite) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pd.read_csv(r"C:\Users\afora\Desktop\Projects\Project_EDA\Data\stackoverflow_survey_2025.txt")

Initial Observation: Pandas detected mixed data types in several columns during dataset import. These columns will be investigated during the data profiling and cleaning stages to determine whether the mixed types represent legitimate categorical responses, missing-value representations, or inconsistent data entry.

In [3]:
dataset.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [4]:
dataset.info()    # Here we can see that dataset has too many columns and mixed data.

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), str(119)
memory usage: 64.6 MB

In [5]:
dataset.shape

(49191, 172)

In [6]:
dataset.columns[0:100]    # printing columns in batches

Index(['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment',
       'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode',
       'LearnCodeAI', 'AILearnHow', 'YearsCode', 'DevType', 'OrgSize',
       'ICorPM', 'RemoteWork', 'PurchaseInfluence', 'TechEndorseIntro',
       'TechEndorse_1', 'TechEndorse_2', 'TechEndorse_3', 'TechEndorse_4',
       'TechEndorse_5', 'TechEndorse_6', 'TechEndorse_7', 'TechEndorse_8',
       'TechEndorse_9', 'TechEndorse_13', 'TechEndorse_13_TEXT',
       'TechOppose_1', 'TechOppose_2', 'TechOppose_3', 'TechOppose_5',
       'TechOppose_7', 'TechOppose_9', 'TechOppose_11', 'TechOppose_13',
       'TechOppose_16', 'TechOppose_15', 'TechOppose_15_TEXT', 'Industry',
       'JobSatPoints_1', 'JobSatPoints_2', 'JobSatPoints_3', 'JobSatPoints_4',
       'JobSatPoints_5', 'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8',
       'JobSatPoints_9', 'JobSatPoints_10', 'JobSatPoints_11',
       'JobSatPoints_13', 'JobSatPoints_14', 'JobSatPoints_15',
       'JobSatPoints_16', 'JobSatPoints_15_TEXT', 'AIThreat', 'NewRole',
       'ToolCountWork', 'ToolCountPersonal', 'Country', 'Currency',
       'CompTotal', 'LanguageChoice', 'LanguageHaveWorkedWith',
       'LanguageWantToWorkWith', 'LanguageAdmired', 'LanguagesHaveEntry',
       'LanguagesWantEntry', 'DatabaseChoice', 'DatabaseHaveWorkedWith',
       'DatabaseWantToWorkWith', 'DatabaseAdmired', 'DatabaseHaveEntry',
       'DatabaseWantEntry', 'PlatformChoice', 'PlatformHaveWorkedWith',
       'PlatformWantToWorkWith', 'PlatformAdmired', 'PlatformHaveEntry',
       'PlatformWantEntry', 'WebframeChoice', 'WebframeHaveWorkedWith',
       'WebframeWantToWorkWith', 'WebframeAdmired', 'WebframeHaveEntry',
       'WebframeWantEntry', 'DevEnvsChoice', 'DevEnvsHaveWorkedWith',
       'DevEnvsWantToWorkWith', 'DevEnvsAdmired', 'DevEnvHaveEntry',
       'DevEnvWantEntry', 'SOTagsHaveWorkedWith', 'SOTagsWantToWorkWith',
       'SOTagsAdmired', 'SOTagsHaveEntry', 'SOTagsWant Entry',
       'OpSysPersonal use'],
      dtype='str')

In [7]:
dataset.columns[100:172]

Index(['OpSysProfessional use', 'OfficeStackAsyncHaveWorkedWith',
       'OfficeStackAsyncWantToWorkWith', 'OfficeStackAsyncAdmired',
       'OfficeStackHaveEntry', 'OfficeStackWantEntry',
       'CommPlatformHaveWorkedWith', 'CommPlatformWantToWorkWith',
       'CommPlatformAdmired', 'CommPlatformHaveEntr', 'CommPlatformWantEntr',
       'AIModelsChoice', 'AIModelsHaveWorkedWith', 'AIModelsWantToWorkWith',
       'AIModelsAdmired', 'AIModelsHaveEntry', 'AIModelsWantEntry',
       'SOAccount', 'SOVisitFreq', 'SODuration', 'SOPartFreq',
       'SO_Dev_Content', 'SO_Actions_1', 'SO_Actions_16', 'SO_Actions_3',
       'SO_Actions_4', 'SO_Actions_5', 'SO_Actions_6', 'SO_Actions_9',
       'SO_Actions_7', 'SO_Actions_10', 'SO_Actions_15', 'SO_Actions_15_TEXT',
       'SOComm', 'SOFriction', 'AISelect', 'AISent', 'AIAcc', 'AIComplex',
       'AIToolCurrently partially AI',
       'AIToolDon't plan to use AI for this task',
       'AIToolPlan to partially use AI', 'AIToolPlan to mostly use AI',
       'AIToolCurrently mostly AI', 'AIFrustration', 'AIExplain', 'AIAgents',
       'AIAgentChange', 'AIAgent_Uses', 'AgentUsesGeneral',
       'AIAgentImpactSomewhat agree', 'AIAgentImpactNeutral',
       'AIAgentImpactSomewhat disagree', 'AIAgentImpactStrongly agree',
       'AIAgentImpactStrongly disagree', 'AIAgentChallengesNeutral',
       'AIAgentChallengesSomewhat disagree', 'AIAgentChallengesStrongly agree',
       'AIAgentChallengesSomewhat agree', 'AIAgentChallengesStrongly disagree',
       'AIAgentKnowledge', 'AIAgentKnowWrite', 'AIAgentOrchestration',
       'AIAgentOrchWrite', 'AIAgentObserveSecure', 'AIAgentObsWrite',
       'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman', 'AIOpen',
       'ConvertedCompYearly', 'JobSat'],
      dtype='str')

# >>> Layer 2: 
* using pandas methods to know more about new filtered dataset.
* Making a new dataset which has required cols for my project.
* Also cleaning some data to make data quality better and make it more consistent.

In [8]:
cols = [
    'ResponseId', 'Age', 'Country', 'EdLevel',
    'MainBranch', 'Employment', 'DevType', 'Industry',
    'WorkExp', 'YearsCode', 'OrgSize', 'RemoteWork', 'ICorPM',
    'LearnCode', 'LearnCodeAI', 'AILearnHow',
    'ConvertedCompYearly', 'JobSat',
    'LanguageHaveWorkedWith', 'LanguageWantToWorkWith', 'LanguageAdmired',
    'DatabaseHaveWorkedWith', 'PlatformHaveWorkedWith', 'DevEnvsHaveWorkedWith',
    'AISelect', 'AISent', 'AIAcc', 'AIComplex', 'AIThreat',
    'AIFrustration', 'AIModelsHaveWorkedWith', 'AIAgents',
]

data = dataset[cols]

In [9]:
data.info()  # getting info of each column and its data.

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Data columns (total 32 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ResponseId              49191 non-null  int64
 1   Age                     49191 non-null  str
 2   Country                 35437 non-null  str
 3   EdLevel                 48149 non-null  str
 4   MainBranch              49191 non-null  str
 5   Employment              48339 non-null  str
 6   DevType                 43680 non-null  str
 7   Industry                33642 non-null  str
 8   WorkExp                 42893 non-null  float64
 9   YearsCode               43042 non-null  float64
 10  OrgSize                 34178 non-null  str
 11  RemoteWork              33780 non-null  str
 12  ICorPM                  33243 non-null  str
 13  LearnCode               33556 non-null  str
 14  LearnCodeAI             45201 non-null  str
 15  AILearnHow              28257 non-null  str
 16  ConvertedCompYearly     23947 non-null  float64
 17  JobSat                  26670 non-null  float64
 18  LanguageHaveWorkedWith  31671 non-null  str
 19  LanguageWantToWorkWith  27079 non-null  str
 20  LanguageAdmired         23470 non-null  str
 21  DatabaseHaveWorkedWith  25550 non-null  str
 22  PlatformHaveWorkedWith  24258 non-null  str
 23  DevEnvsHaveWorkedWith   26019 non-null  str
 24  AISelect                33720 non-null  str
 25  AISent                  33467 non-null  str
 26  AIAcc                   33297 non-null  str
 27  AIComplex               33283 non-null  str
 28  AIThreat                36078 non-null  str
 29  AIFrustration           31522 non-null  str
 30  AIModelsHaveWorkedWith  16281 non-null  str
 31  AIAgents                31919 non-null  str
dtypes: float64(4), int64(1), str(27)
memory usage: 12.0 MB

Here we can see that there are some null values in our data.

In [10]:
data.iloc[:,20:30].info()

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   LanguageAdmired         23470 non-null  str
 1   DatabaseHaveWorkedWith  25550 non-null  str
 2   PlatformHaveWorkedWith  24258 non-null  str
 3   DevEnvsHaveWorkedWith   26019 non-null  str
 4   AISelect                33720 non-null  str
 5   AISent                  33467 non-null  str
 6   AIAcc                   33297 non-null  str
 7   AIComplex               33283 non-null  str
 8   AIThreat                36078 non-null  str
 9   AIFrustration           31522 non-null  str
dtypes: str(10)
memory usage: 3.8 MB

In [11]:
data.isnull().sum()

ResponseId                    0
Age                           0
Country                   13754
EdLevel                    1042
MainBranch                    0
Employment                  852
DevType                    5511
Industry                  15549
WorkExp                    6298
YearsCode                  6149
OrgSize                   15013
RemoteWork                15411
ICorPM                    15948
LearnCode                 15635
LearnCodeAI                3990
AILearnHow                20934
ConvertedCompYearly       25244
JobSat                    22521
LanguageHaveWorkedWith    17520
LanguageWantToWorkWith    22112
LanguageAdmired           25721
DatabaseHaveWorkedWith    23641
PlatformHaveWorkedWith    24933
DevEnvsHaveWorkedWith     23172
AISelect                  15471
AISent                    15724
AIAcc                     15894
AIComplex                 15908
AIThreat                  13113
AIFrustration             17669
AIModelsHaveWorkedWith    32910
AIAgents                  17272
dtype: int64

In [12]:
data.duplicated().sum() # -- very good thing that we do not have duplicated values

np.int64(0)

In [13]:
data.describe()

,ResponseId,WorkExp,YearsCode,ConvertedCompYearly,JobSat
count,49191.000000,42893.000000,43042.000000,2.394700e+04,26670.000000
mean,24596.000000,13.367403,16.570861,1.017615e+05,7.201950
std,14200.362883,10.800117,11.787610,4.617569e+05,1.997245
min,1.000000,1.000000,1.000000,1.000000e+00,0.000000
25%,12298.500000,5.000000,8.000000,3.817100e+04,6.000000
50%,24596.000000,10.000000,14.000000,7.532000e+04,8.000000
75%,36893.500000,20.000000,24.000000,1.205960e+05,8.000000
max,49191.000000,100.000000,100.000000,5.000000e+07,10.000000

In [14]:
data.isna().sum()  # There are only 4 fully filled columns.

ResponseId                    0
Age                           0
Country                   13754
EdLevel                    1042
MainBranch                    0
Employment                  852
DevType                    5511
Industry                  15549
WorkExp                    6298
YearsCode                  6149
OrgSize                   15013
RemoteWork                15411
ICorPM                    15948
LearnCode                 15635
LearnCodeAI                3990
AILearnHow                20934
ConvertedCompYearly       25244
JobSat                    22521
LanguageHaveWorkedWith    17520
LanguageWantToWorkWith    22112
LanguageAdmired           25721
DatabaseHaveWorkedWith    23641
PlatformHaveWorkedWith    24933
DevEnvsHaveWorkedWith     23172
AISelect                  15471
AISent                    15724
AIAcc                     15894
AIComplex                 15908
AIThreat                  13113
AIFrustration             17669
AIModelsHaveWorkedWith    32910
AIAgents                  17272
dtype: int64

In [15]:
data.sample()

,ResponseId,Age,Country,EdLevel,MainBranch,Employment,DevType,Industry,WorkExp,YearsCode,...,PlatformHaveWorkedWith,DevEnvsHaveWorkedWith,AISelect,AISent,AIAcc,AIComplex,AIThreat,AIFrustration,AIModelsHaveWorkedWith,AIAgents
14411,14412,35-44 years old,Switzerland,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",I am a developer by profession,Employed,"Developer, back-end",Fintech,21.0,25.0,...,Ansible;Composer;Docker;Homebrew;Kubernetes;np...,Eclipse;IntelliJ IDEA;Trae;Vim;Visual Studio C...,"Yes, I use AI tools monthly or infrequently",Indifferent,Highly distrust,Neither good or bad at handling complex tasks,I'm not sure,"AI solutions that are almost right, but not qu...",Anthropic: Claude Sonnet;Meta Llama (all models),"No, and I don't plan to"

In [16]:
data['Age'].value_counts()
data['Employment'].value_counts()
data['Country'].nunique()
data['EdLevel'].value_counts()
data['MainBranch'].value_counts()
data['Employment'].value_counts()
data['DevType'].value_counts()
data['DevType'].nunique()

32

In [49]:
data.iloc[:,20:32].info()

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   LanguageAdmired         23470 non-null  str
 1   DatabaseHaveWorkedWith  25550 non-null  str
 2   PlatformHaveWorkedWith  24258 non-null  str
 3   DevEnvsHaveWorkedWith   26019 non-null  str
 4   AISelect                33720 non-null  str
 5   AISent                  33467 non-null  str
 6   AIAcc                   33297 non-null  str
 7   AIComplex               33283 non-null  str
 8   AIThreat                36078 non-null  str
 9   AIFrustration           31522 non-null  str
 10  AIModelsHaveWorkedWith  16281 non-null  str
 11  AIAgents                31919 non-null  str
dtypes: str(12)
memory usage: 4.5 MB

In [65]:
data['AIAgents'].value_counts()

AIAgents
No, and I don't plan to                                  12082
No, but I plan to                                         5561
Yes, I use AI agents at work daily                        4509
No, I use AI exclusively in copilot/autocomplete mode     4401
Yes, I use AI agents at work weekly                       2868
Yes, I use AI agents at work monthly or infrequently      2498
Name: count, dtype: int64

In [63]:
data['AIFrustration'].nunique()

100

In [ ]:
data['LanguageHaveWorkedWith'] = data['LanguageHaveWorkedWith'].str.replace(';')

In [44]:
data['ConvertedCompYearly'].describe

count    2.394700e+04
mean     1.017615e+05
std      4.617569e+05
min      1.000000e+00
25%      3.817100e+04
50%      7.532000e+04
75%      1.205960e+05
max      5.000000e+07
Name: ConvertedCompYearly, dtype: float64

In [39]:
data['AILearnHow'].nunique()

1677

In [40]:
data['AILearnHow'] = data['AILearnHow'].str.split(';').str[0]

In [41]:
data['AILearnHow'].value_counts()

AILearnHow
AI CodeGen tools or AI-enabled apps                                       14824
Technical documentation (is generated for/by the tool or system)           5370
Videos (not associated with specific online course or certification)       2936
Other online resources (e.g. standard search, forum, online community)     2042
Colleague or on-the-job training                                           1041
Online Courses or Certification (includes all media types)                  576
Other (please specify):                                                     549
Blogs or podcasts                                                           352
School (i.e., University, College, etc)                                     186
Stack Overflow or Stack Exchange                                            143
Books / Physical media                                                       91
Games or coding challenges                                                   79
Coding Bootcamp                                                              68
Name: count, dtype: int64

In [ ]:

data['AIComplex'] = data['AIComplex'].replace({
    'Good, but not great at handling complex tasks': 'Good',
    'Bad at handling complex tasks': 'Bad',
    'Very poor at handling complex tasks': 'Very poor',
    "I don't use AI tools for complex tasks / I don't know": 'Not sure',
    'Neither good or bad at handling complex tasks': 'Neutral',
    'Very well at handling complex tasks': 'Very well',
})

data['MainBranch'] = data['MainBranch'].replace({
    'I am a developer by profession': 'Developer',
    'I am not primarily a developer, but I write code sometimes as part of my work/studies': 'Occasional coder',
    'I am learning to code': 'Learner',
    'I code primarily as a hobby': 'Hobbyist',
    'I used to be a developer by profession, but no longer am': 'Former developer',
    'I work with developers or my work supports developers but am not a developer by profession': 'Dev-adjacent'
})


data['EdLevel'] = data['EdLevel'].replace({
    'Bachelor’s degree (B.A., B.S., B.Eng., etc.)': 'Bachelor',
    'Master’s degree (M.A., M.S., M.Eng., MBA, etc.)': 'Master',
    'Some college/university study without earning a degree': 'Some college',
    'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)': 'Secondary school',
    'Professional degree (JD, MD, Ph.D, Ed.D, etc.)': 'Professional/PhD',
    'Associate degree (A.A., A.S., etc.)': 'Associate',
    'Other (please specify):': 'Other',
    'Primary/elementary school': 'Primary school'
})


data['Employment'] = data['Employment'].replace({
    'Independent contractor, freelancer, or self-employed':'Contractor/Freelancer',
    'I prefer not to say':'Not mentioned'
})

data['Age'] = data['Age'].replace({
    '25-34 years old':'25-34',
    '35-44 years old':'35-44',
    '18-24 years old':'18-24',
    '45-54 years old':'45-54',
    '55-64 years old':'55-64',
    '65 years or older':'65+',
    'Prefer not to say':'Not mentioned'
})

data['DevType'] = data['DevType'].replace({
    'Developer, full-stack': 'Software Developer',
    'Developer, back-end': 'Software Developer',
    'Developer, front-end': 'Software Developer',
    'Developer, desktop or enterprise applications': 'Software Developer',
    'Developer, mobile': 'Software Developer',
    'Developer, embedded applications or devices': 'Software Developer',
    'Developer, game or graphics': 'Software Developer',
    'Developer, QA or test': 'Software Developer',
    'Architect, software or solutions': 'Software Developer',

    'Data engineer': 'Data & AI',
    'Data scientist': 'Data & AI',
    'AI/ML engineer': 'Data & AI',
    'Data or business analyst': 'Data & AI',
    'Developer, AI apps or physical AI': 'Data & AI',
    'Applied scientist': 'Data & AI',

    'DevOps engineer or professional': 'Infra & Security',
    'Cloud infrastructure engineer': 'Infra & Security',
    'System administrator': 'Infra & Security',
    'Database administrator or engineer': 'Infra & Security',
    'Cybersecurity or InfoSec professional': 'Infra & Security',
    'Support engineer or analyst': 'Infra & Security',

    'Engineering manager': 'Management',
    'Project manager': 'Management',
    'Product manager': 'Management',
    'Senior executive (C-suite, VP, etc.)': 'Management',
    'Founder, technology or otherwise': 'Management',

    'UX, Research Ops or UI design professional': 'Other',
    'Financial analyst or engineer': 'Other',
    'Other (please specify):': 'Other',

    'Academic researcher': 'Academic/Researcher',
})

data['OrgSize'] = data['OrgSize'].replace({
    'Just me - I am a freelancer, sole proprietor, etc.': 'Solo',
    'Less than 20 employees': '<20',
    '20 to 99 employees': '20-99',
    '100 to 499 employees': '100-499',
    '500 to 999 employees': '500-999',
    '1,000 to 4,999 employees': '1000-4999',
    '5,000 to 9,999 employees': '5000-9999',
    '10,000 or more employees': '10000+',
    'I don’t know': 'Not mentioned'
})

data['RemoteWork'] = data['RemoteWork'].replace({
    'Hybrid (some remote, leans heavy to in-person)': 'Hybrid (office-leaning)',
    'Hybrid (some in-person, leans heavy to flexibility)': 'Hybrid (remote-leaning)',
    'Your choice (very flexible, you can come in when you want or just as needed)': 'Flexible'
})

data['LearnCodeAI'] = data['LearnCodeAI'].replace({
    'Yes, I learned how to use AI-enabled tools required for my job or to benefit my career': 'Yes',
    'Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies': 'Yes',
    'No, I learned something that was not related to AI or AI enablement for my personal curiosity and/or hobbies': 'No',
    "No, I didn't spend time learning in the past year": 'No',
    'No, I learned something that was not related to AI or AI enablement as required for my job or to benefit my career': 'No'
})

data['AILearnHow'] = data['AILearnHow'].replace({
    'AI CodeGen tools or AI-enabled apps': 'AI tools',
    'Technical documentation (is generated for/by the tool or system)': 'Documentation',
    'Videos (not associated with specific online course or certification)': 'Videos',
    'Other online resources (e.g. standard search, forum, online community)': 'Online resources',
    'Colleague or on-the-job training': 'On-the-job',
    'Online Courses or Certification (includes all media types)': 'Online courses',
    'Other (please specify):': 'Other',
    'Blogs or podcasts': 'Blogs/Podcasts',
    'School (i.e., University, College, etc)': 'School',
    'Stack Overflow or Stack Exchange': 'Stack Overflow',
    'Books / Physical media': 'Books',
    'Games or coding challenges': 'Games/Challenges',
    'Coding Bootcamp': 'Bootcamp',
})

data['AISelect'] = data['AISelect'].replace({
    'Yes, I use AI tools daily': 'Yes - daily',
    'Yes, I use AI tools weekly': 'Yes - weekly',
    "No, and I don't plan to": 'No',
    'Yes, I use AI tools monthly or infrequently': 'Yes - sometimes',
    'No, but I plan to soon': 'No - but want to',
})

data['AIAgents'] = data['AIAgents'].replace({
    'Yes, I use AI agents at work daily': 'Yes - daily',
    'Yes, I use AI agents at work weekly': 'Yes - weekly',
    'Yes, I use AI agents at work monthly or infrequently': 'Yes - sometimes',
    "No, and I don't plan to": 'No',
    'No, but I plan to': 'No - but want to',
    'No, I use AI exclusively in copilot/autocomplete mode': 'No - copilot only',
})

KeyError: 'AIComplex'

In [19]:
(data['Age'] == 'Prefer not to say').sum()

np.int64(0)

In [20]:
data['DevType'].value_counts()

DevType
Software Developer     28840
Student                 3008
Data & AI               2905
Infra & Security        2770
Management              2534
Other                   2034
Academic/Researcher     1131
Retired                  458
Name: count, dtype: int64

In [21]:
data['DevType'].value_counts().to_string()

'DevType\nSoftware Developer     28840\nStudent                 3008\nData & AI               2905\nInfra & Security        2770\nManagement              2534\nOther                   2034\nAcademic/Researcher     1131\nRetired                  458'

# Level 3 -- Cleaning and making final ready dataset.

* I will be renaming different columns and values to be relevant.
* Finally will run the full assessment just to check the final dataset.
* To make any further changes - will use Define, code then test method.

In [71]:
data.sample(3)

,ResponseId,Age,Country,EdLevel,MainBranch,Employment,DevType,Industry,WorkExp,YearsCode,...,PlatformHaveWorkedWith,DevEnvsHaveWorkedWith,AISelect,AISent,AIAcc,AIComplex,AIThreat,AIFrustration,AIModelsHaveWorkedWith,AIAgents
32269,32270,Not mentioned,New Zealand,Secondary school,Hobbyist,Student,Student,NaN,NaN,4.0,...,APT;Cargo;Docker;Make;Maven (build tool);Ninja...,Android Studio;Eclipse;IntelliJ IDEA;Notepad++...,No,Unfavorable,Highly distrust,Bad,No,"AI solutions that are almost right, but not qu...",NaN,No - copilot only
35131,35132,25-34,Zambia,Bachelor,Developer,Employed,Software Developer,Retail and Consumer Services,5.0,11.0,...,Microsoft Azure;npm;NuGet;Vite;Webpack,Android Studio;Rider;Visual Studio;Visual Stud...,Yes - daily,Indifferent,Somewhat distrust,Bad,No,"AI solutions that are almost right, but not qu...",DeepSeek (R- Reasoning models);openAI GPT (cha...,No
43279,43280,18-24,NaN,Bachelor,Developer,Student,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
data.columns

# Renaming the cols to improve the readability and context. 

data = data.rename(columns={
    'ResponseId': 'ID',
    'EdLevel': 'Education_level',
    'MainBranch': 'Main_Branch',
    'DevType': 'Job_title',
    'WorkExp': 'Work_exp',
    'YearsCode': 'Years_coding',
    'OrgSize': 'Org_size',
    'RemoteWork': 'Work_mode',
    'ICorPM': 'Role_type',
    'LearnCodeAI': 'Learned_AI_tools',
    'AILearnHow': 'AI_learning_source',
    'ConvertedCompYearly': 'Salary_USD',
    'JobSat': 'Job_satisfaction',
    'LanguageHaveWorkedWith': 'Languages_used',
    'LanguageWantToWorkWith': 'Languages_wanted',
    'LanguageAdmired': 'Languages_admired',
    'DatabaseHaveWorkedWith': 'Databases_used',
    'PlatformHaveWorkedWith': 'Platforms_used',
    'DevEnvsHaveWorkedWith': 'Dev_environments',
    'AISelect': 'AI_usage',
    'AISent': 'AI_sentiment',
    'AIAcc': 'AI_accuracy_trust',
    'AIComplex': 'AI_handling_complex_tasks',
    'AIThreat': 'AI_job_threat',
    'AIFrustration': 'AI_frustrations',
    'AIModelsHaveWorkedWith': 'AI_models_used',
    'AIAgents': 'AI_agents_usage',
})

In [73]:
# running full accessment

data.info()

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Data columns (total 32 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         49191 non-null  int64
 1   Age                        49191 non-null  str
 2   Country                    35437 non-null  str
 3   Education_level            48149 non-null  str
 4   Main_Branch                49191 non-null  str
 5   Employment                 48339 non-null  str
 6   Job_title                  43680 non-null  str
 7   Industry                   33642 non-null  str
 8   Work_exp                   42893 non-null  float64
 9   Years_coding               43042 non-null  float64
 10  Org_size                   34178 non-null  str
 11  Work_mode                  33780 non-null  str
 12  Role_type                  33243 non-null  str
 13  LearnCode                  33556 non-null  str
 14  Learned_AI_tools           45201 non-null  str
 15  AI_learning_source         28257 non-null  object
 16  Salary_USD                 23947 non-null  float64
 17  Job_satisfaction           26670 non-null  float64
 18  Languages_used             31671 non-null  str
 19  Languages_wanted           27079 non-null  str
 20  Languages_admired          23470 non-null  str
 21  Databases_used             25550 non-null  str
 22  Platforms_used             24258 non-null  str
 23  Dev_environments           26019 non-null  str
 24  AI_usage                   33720 non-null  str
 25  AI_sentiment               33467 non-null  str
 26  AI_accuracy_trust          33297 non-null  str
 27  AI_handling_complex_tasks  33283 non-null  str
 28  AI_job_threat              36078 non-null  str
 29  AI_frustrations            31522 non-null  str
 30  AI_models_used             16281 non-null  str
 31  AI_agents_usage            31919 non-null  str
dtypes: float64(4), int64(1), object(1), str(26)
memory usage: 12.0+ MB

In [74]:
data.iloc[:,20:30].info()

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Languages_admired          23470 non-null  str
 1   Databases_used             25550 non-null  str
 2   Platforms_used             24258 non-null  str
 3   Dev_environments           26019 non-null  str
 4   AI_usage                   33720 non-null  str
 5   AI_sentiment               33467 non-null  str
 6   AI_accuracy_trust          33297 non-null  str
 7   AI_handling_complex_tasks  33283 non-null  str
 8   AI_job_threat              36078 non-null  str
 9   AI_frustrations            31522 non-null  str
dtypes: str(10)
memory usage: 3.8 MB

In [130]:
data.describe()  # Here we can see some suspecious values like 100 years of work exp.
# Plan is to make new clean columns for operations that get affected by outliers.

,ID,Work_exp,Years_coding,Salary_USD,Job_satisfaction
count,49191.000000,42893.000000,43042.000000,2.394700e+04,26670.000000
mean,24596.000000,13.367403,16.570861,1.017615e+05,7.201950
std,14200.362883,10.800117,11.787610,4.617569e+05,1.997245
min,1.000000,1.000000,1.000000,1.000000e+00,0.000000
25%,12298.500000,5.000000,8.000000,3.817100e+04,6.000000
50%,24596.000000,10.000000,14.000000,7.532000e+04,8.000000
75%,36893.500000,20.000000,24.000000,1.205960e+05,8.000000
max,49191.000000,100.000000,100.000000,5.000000e+07,10.000000

In [ ]:
data = data.drop(columns=['LearnCode'])  # dropping irrelevent column.

In [ ]:
data.isnull().sum()
data.duplicated().sum()

np.int64(0)

In [82]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [89]:
data.sample(3)

,ID,Age,Country,Education_level,Main_Branch,Employment,Job_title,Industry,Work_exp,Years_coding,Org_size,Work_mode,Role_type,Learned_AI_tools,AI_learning_source,Salary_USD,Job_satisfaction,Languages_used,Languages_wanted,Languages_admired,Databases_used,Platforms_used,Dev_environments,AI_usage,AI_sentiment,AI_accuracy_trust,AI_handling_complex_tasks,AI_job_threat,AI_frustrations,AI_models_used,AI_agents_usage
39978,39979,45-54,Germany,Master,Developer,Employed,Software Developer,Software Development,20.0,NaN,20-99,Hybrid (remote-leaning),Individual contributor,Yes,AI tools,110214.0,6.0,Go;JavaScript;Kotlin,Go;JavaScript;Kotlin,Go;JavaScript;Kotlin,BigQuery;Cloud Firestore;MySQL,Google Cloud,Android Studio;Visual Studio Code,Yes - daily,Very favorable,Somewhat trust,Very well,Yes,"AI solutions that are almost right, but not quite",Gemini (Flash general purpose models);Gemini (Pro Reasoning models);openAI GPT (chatbot models);openAI Reasoning models,Yes - weekly
29697,29698,25-34,Kenya,Some college,Developer,contractor/freelancer,Software Developer,Software Development,3.0,5.0,<20,Remote,People manager,Yes,AI tools,30000.0,5.0,Bash/Shell (all shells);C;JavaScript;Ruby,NaN,NaN,PostgreSQL;SQLite,Amazon Web Services (AWS);Datadog;Digital Ocean;Docker;Google Cloud;Microsoft Azure;Vercel;Vite;Webpack,NaN,Yes - weekly,Favorable,Somewhat trust,Good,No,"AI solutions that are almost right, but not quite;Debugging AI-generated code is more time-consuming",openAI GPT (chatbot models),No - but want to
27920,27921,25-34,Colombia,Bachelor,Dev-adjacent,Employed,Data & AI,Other:,4.0,7.0,100-499,Remote,Individual contributor,Yes,Documentation,14681.0,NaN,JavaScript;Python;SQL,C#;Visual Basic (.Net),NaN,Databricks SQL;Microsoft SQL Server;PostgreSQL;SQLite,Docker;Microsoft Azure;Pip,Claude Code;Cursor;Jupyter Notebook/JupyterLab;PyCharm;Visual Studio Code,Yes - daily,Favorable,Somewhat distrust,Bad,Yes,Debugging AI-generated code is more time-consuming;It’s hard to understand how or why the code works,Alibaba Cloud Qwen models;Anthropic: Claude Sonnet;DeepSeek (V- General purpose models);Gemini (Flash general purpose models);Gemini (Pro Reasoning models);Meta Llama (all models);Microsoft Phi-4 models;Mistral AI models;openAI GPT (chatbot models),Yes - daily

In [84]:
data['Main_Branch'].value_counts()

Main_Branch
Developer           37467
Occasional coder     4894
Learner              2585
Hobbyist             1924
Former developer     1325
Dev-adjacent          996
Name: count, dtype: int64

In [ ]:
back_up = data.copy() # making a backup

In [87]:
dataset['DevType']

0                       Developer, mobile
1                     Developer, back-end
2                    Developer, front-end
3                     Developer, back-end
4                     Engineering manager
                       ...
49186                                 NaN
49187                                 NaN
49188    Architect, software or solutions
49189                                 NaN
49190                             Student
Name: DevType, Length: 49191, dtype: str

In [ ]:
data.sort_values('Salary_USD')  # Here Salary_USD = 1.0 is just not a good data and its junk.

,ID,Age,Country,Education_level,Main_Branch,Employment,Job_title,Industry,Work_exp,Years_coding,Org_size,Work_mode,Role_type,Learned_AI_tools,AI_learning_source,Salary_USD,Job_satisfaction,Languages_used,Languages_wanted,Languages_admired,Databases_used,Platforms_used,Dev_environments,AI_usage,AI_sentiment,AI_accuracy_trust,AI_handling_complex_tasks,AI_job_threat,AI_frustrations,AI_models_used,AI_agents_usage
34865,34866,35-44,Antigua and Barbuda,Master,Developer,Employed,Software Developer,Software Development,16.0,20.0,20-99,Remote,Individual contributor,Yes,AI tools,1.0,8.0,Bash/Shell (all shells);C;Go;HTML/CSS;JavaScript;PHP;PowerShell;Python;TypeScript,NaN,NaN,MariaDB;PostgreSQL;SQLite;Supabase,APT;Bun;Cargo;Composer;Docker;Kubernetes;Make;npm;Pip;pnpm;Vite;Webpack;Yarn,Aider;IntelliJ IDEA;Neovim;PhpStorm;PyCharm;Sublime Text;Vim;Visual Studio Code,Yes - daily,Favorable,Highly distrust,Very poor,No,"AI solutions that are almost right, but not quite;Debugging AI-generated code is more time-consuming;I’ve become less confident in my own problem-solving",Alibaba Cloud Qwen models;Anthropic: Claude Sonnet;DeepSeek (R- Reasoning models);Gemini (Flash general purpose models);Gemini (Pro Reasoning models);openAI GPT (chatbot models);openAI Reasoning models;X Grok models,Yes - weekly
42078,42079,25-34,Ethiopia,Some college,Dev-adjacent,Student,Data & AI,NaN,12.0,2.0,NaN,NaN,NaN,Yes,Online resources,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes - weekly,Very unfavorable,Somewhat trust,Good,Yes,I’ve become less confident in my own problem-solving,NaN,Yes - daily
48600,48601,25-34,Nomadic,Bachelor,Former developer,Employed,Infra & Security,Other:,3.0,2.0,20-99,Hybrid (office-leaning),People manager,Yes,On-the-job,1.0,NaN,Bash/Shell (all shells);C;C#;HTML/CSS;Java;JavaScript;PHP;PowerShell;Python,Bash/Shell (all shells);Java;Python;R;Ruby,Bash/Shell (all shells);Java;Python,MariaDB;Microsoft Access;Microsoft SQL Server;MongoDB;MySQL;Neo4J,Amazon Web Services (AWS);Cloudflare;Google Cloud;IBM Cloud;Kubernetes;Microsoft Azure,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN
20026,20027,35-44,Turkey,Bachelor,Developer,Employed,Infra & Security,Software Development,16.0,9.0,10000+,Remote,Individual contributor,No,NaN,1.0,7.0,Bash/Shell (all shells);Go;Lua,NaN,NaN,Elasticsearch;PostgreSQL;Redis,Amazon Web Services (AWS);Ansible;Docker;Kubernetes;Podman;Prometheus;Terraform,Neovim;Vim;Visual Studio Code,No,Unfavorable,Somewhat distrust,Very poor,No,Debugging AI-generated code is more time-consuming;I don’t use AI tools regularly,NaN,No
12407,12408,25-34,Indonesia,Bachelor,Developer,Employed,Software Developer,Software Development,5.0,7.0,20-99,In-person,Individual contributor,No,NaN,1.0,6.0,Bash/Shell (all shells);C;C++;Go;Groovy;HTML/CSS;Java;Kotlin;PowerShell;Python;SQL,Bash/Shell (all shells);Elixir;Erlang;Go;Groovy;Java;OCaml;PowerShell;Python;Rust;SQL;Zig,Bash/Shell (all shells);Go;Groovy;Java;PowerShell;Python;SQL,H2;Oracle;PostgreSQL;Redis,Amazon Web Services (AWS);Chocolatey;Datadog;Docker;Gradle;Kubernetes;Maven (build tool);npm;Pip;Podman;Poetry;Terraform;Yarn,Android Studio;IntelliJ IDEA;Vim;Visual Studio Code,Yes - daily,Very favorable,Somewhat trust,Very poor,I'm not sure,Debugging AI-generated code is more time-consuming;I haven’t encountered any problems,Anthropic: Claude Sonnet;openAI GPT (chatbot models);openAI Image generating models;openAI Reasoning models,Yes - sometimes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,49187,18-24,NaN,Bachelor,Hobbyist,Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,49188,45-54,NaN,Some college,Developer,Employed,NaN,NaN,25.0,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,49189,35-44,Italy,Master,Developer,Employed,Software Developer,Banking/Financial Services,17.0,31.0,10000+,Hybrid (remote-leaning),People manager,Yes,AI tools,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,Yes - sometimes,Favorable,Neither trust nor distrust,Good,No,"AI solutions that are almost right, but not quite;Debugging AI-generated code is more time-consuming;I don’t use AI tools regularly",NaN,No - copilot only
49189,49190,25-34,NaN,Professional/PhD,Developer,contractor/freelancer,NaN,NaN,2.0,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49190,49191,18-24,NaN,Some college,Occasional coder,Student,Student,NaN,NaN,6.0,NaN,NaN,NaN,Yes,AI tools,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [94]:
dataset['ConvertedCompYearly'].value_counts()

ConvertedCompYearly
69609.0     328
58007.0     270
92812.0     269
81210.0     266
116015.0    263
           ...
167954.0      1
15379.0       1
138470.0      1
5825.0        1
69008.0       1
Name: count, Length: 6237, dtype: int64

In [97]:
data['Salary_USD'].sort_values(na_position='first')

13              NaN
14              NaN
15              NaN
17              NaN
18              NaN
            ...
45971    13921760.0
35353    15430267.0
43143    18387548.0
28700    33552715.0
34267    50000000.0
Name: Salary_USD, Length: 49191, dtype: float64

In [106]:
data[data['Salary_USD'] == 1.0 ].count()

ID                           28
Age                          28
Country                      28
Education_level              28
Main_Branch                  28
Employment                   28
Job_title                    28
Industry                     20
Work_exp                     26
Years_coding                 27
Org_size                     16
Work_mode                    16
Role_type                    15
Learned_AI_tools             28
AI_learning_source           21
Salary_USD                   28
Job_satisfaction             15
Languages_used               17
Languages_wanted             10
Languages_admired             8
Databases_used               15
Platforms_used               12
Dev_environments             14
AI_usage                     21
AI_sentiment                 22
AI_accuracy_trust            19
AI_handling_complex_tasks    20
AI_job_threat                26
AI_frustrations              17
AI_models_used               10
AI_agents_usage              18
dtype: int64

In [110]:
(data['Salary_USD'] < 1000).sum()

np.int64(724)

In [ ]:

data[data['Salary_USD'] < 1000]['Country'].value_counts().head(10)

Country
Ukraine                     80
United States of America    70
Nigeria                     43
India                       42
Brazil                      28
Germany                     23
Colombia                    22
Pakistan                    21
Viet Nam                    18
Kenya                       17
Name: count, dtype: int64

In [112]:
data[data['Salary_USD'] < 1000]['Salary_USD'].describe()

count    724.000000
mean     266.310773
std      282.240147
min        1.000000
25%       38.500000
50%      137.500000
75%      455.250000
max      999.000000
Name: Salary_USD, dtype: float64

Making a new clean column for salaries_USD by keeping its range above 1000 USD and

In [115]:
data['Education_level'].value_counts()

Education_level
Bachelor            20278
Master              12589
Some college         6182
Secondary school     3631
Professional/PhD     2624
Associate            1562
Other                 701
Primary school        582
Name: count, dtype: int64

In [126]:
len(data[data['Salary_USD'] <= 500])

568

In [128]:
data[(data['Salary_USD'] <= 500) & (data['Education_level'].isin(['Primary school','Secondary school','Some college','Other','Associate','Bachelor']))].shape[0]

405

### Observation (Salary_USD):
- Some values are too low to be real salaries, e.g. 1.0 USD per year
- These act as outliers and pull the mean and std toward the low side
- Even though the sample is small relative to the dataset, they distort the average and the spread, so they need handling before analysis
- Plan: keep the raw column, handle outliers separately (cleaned column)

### Making final changes --> 
* Keeping some original numerical columns that have outliers and some unreal values.
* Making new columns with applied conditions for operations that can get affected by those unreal outlier values.
* changing the dtypes of columns to manage the size of data.

In [132]:
data['Salary_USD'] = data['Salary_USD'].astype('float32')
data['Job_satisfaction'] = data['Job_satisfaction'].astype('Int8')
data['Work_exp'] = data['Work_exp'].astype('Int8')
data['Years_coding'] = data['Years_coding'].astype('Int8')

In [133]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Data columns (total 31 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         49191 non-null  int64
 1   Age                        49191 non-null  str
 2   Country                    35437 non-null  str
 3   Education_level            48149 non-null  str
 4   Main_Branch                49191 non-null  str
 5   Employment                 48339 non-null  str
 6   Job_title                  43680 non-null  str
 7   Industry                   33642 non-null  str
 8   Work_exp                   42893 non-null  Int8
 9   Years_coding               43042 non-null  Int8
 10  Org_size                   34178 non-null  str
 11  Work_mode                  33780 non-null  str
 12  Role_type                  33243 non-null  str
 13  Learned_AI_tools           45201 non-null  str
 14  AI_learning_source         28257 non-null  object
 15  Salary_USD                 23947 non-null  float32
 16  Job_satisfaction           26670 non-null  Int8
 17  Languages_used             31671 non-null  str
 18  Languages_wanted           27079 non-null  str
 19  Languages_admired          23470 non-null  str
 20  Databases_used             25550 non-null  str
 21  Platforms_used             24258 non-null  str
 22  Dev_environments           26019 non-null  str
 23  AI_usage                   33720 non-null  str
 24  AI_sentiment               33467 non-null  str
 25  AI_accuracy_trust          33297 non-null  str
 26  AI_handling_complex_tasks  33283 non-null  str
 27  AI_job_threat              36078 non-null  str
 28  AI_frustrations            31522 non-null  str
 29  AI_models_used             16281 non-null  str
 30  AI_agents_usage            31919 non-null  str
dtypes: Int8(3), float32(1), int64(1), object(1), str(25)
memory usage: 10.6+ MB

In [137]:
pd.set_option('display.float_format', '{:,.2f}'.format)
data.describe()

             ID  Work_exp  Years_coding    Salary_USD  Job_satisfaction
count 49,191.00 42,893.00     43,042.00     23,947.00         26,670.00
mean  24,596.00     13.37         16.57    101,761.55              7.20
std   14,200.36     10.80         11.79    461,756.91              2.00
min        1.00      1.00          1.00          1.00              0.00
25%   12,298.50      5.00          8.00     38,171.00              6.00
50%   24,596.00     10.00         14.00     75,320.00              8.00
75%   36,893.50     20.00         24.00    120,596.00              8.00
max   49,191.00    100.00        100.00 50,000,000.00             10.00

In [139]:
print((data['Work_exp'] > 50).sum())
print((data['Years_coding'] > 50).sum())

147
248

In [140]:
data[data['Years_coding'] > 50]['Age'].value_counts()

Age
65+              170
55-64             20
18-24             18
25-34             15
35-44             11
Not mentioned     10
45-54              4
Name: count, dtype: int64

In [142]:
data['Work_exp_clean'] = data['Work_exp'].where(data['Work_exp'] < 65)
data['Years_coding_clean'] = data['Years_coding'].where(data['Years_coding'] <= 65)
data['Salary_clean'] = data['Salary_USD'].where(data['Salary_USD'].between(800, 500_000))

In [145]:
data.describe()

,ID,Work_exp,Years_coding,Salary_USD,Job_satisfaction,Work_exp_clean,Years_coding_clean,Salary_clean
count,"49,191.00","42,893.00","43,042.00","23,947.00","26,670.00","42,842.00","42,983.00","23,100.00"
mean,"24,596.00",13.37,16.57,"101,761.55",7.20,13.27,16.46,"90,866.55"
std,"14,200.36",10.80,11.79,"461,756.91",2.00,10.44,11.44,"71,559.76"
min,1.00,1.00,1.00,1.00,0.00,1.00,1.00,800.00
25%,"12,298.50",5.00,8.00,"38,171.00",6.00,5.00,8.00,"41,531.50"
50%,"24,596.00",10.00,14.00,"75,320.00",8.00,10.00,14.00,"76,097.50"
75%,"36,893.50",20.00,24.00,"120,596.00",8.00,20.00,24.00,"121,415.50"
max,"49,191.00",100.00,100.00,"50,000,000.00",10.00,63.00,65.00,"500,000.00"

In [146]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Data columns (total 34 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         49191 non-null  int64
 1   Age                        49191 non-null  str
 2   Country                    35437 non-null  str
 3   Education_level            48149 non-null  str
 4   Main_Branch                49191 non-null  str
 5   Employment                 48339 non-null  str
 6   Job_title                  43680 non-null  str
 7   Industry                   33642 non-null  str
 8   Work_exp                   42893 non-null  Int8
 9   Years_coding               43042 non-null  Int8
 10  Org_size                   34178 non-null  str
 11  Work_mode                  33780 non-null  str
 12  Role_type                  33243 non-null  str
 13  Learned_AI_tools           45201 non-null  str
 14  AI_learning_source         28257 non-null  object
 15  Salary_USD                 23947 non-null  float32
 16  Job_satisfaction           26670 non-null  Int8
 17  Languages_used             31671 non-null  str
 18  Languages_wanted           27079 non-null  str
 19  Languages_admired          23470 non-null  str
 20  Databases_used             25550 non-null  str
 21  Platforms_used             24258 non-null  str
 22  Dev_environments           26019 non-null  str
 23  AI_usage                   33720 non-null  str
 24  AI_sentiment               33467 non-null  str
 25  AI_accuracy_trust          33297 non-null  str
 26  AI_handling_complex_tasks  33283 non-null  str
 27  AI_job_threat              36078 non-null  str
 28  AI_frustrations            31522 non-null  str
 29  AI_models_used             16281 non-null  str
 30  AI_agents_usage            31919 non-null  str
 31  Work_exp_clean             42842 non-null  Int8
 32  Years_coding_clean         42983 non-null  Int8
 33  Salary_clean               23100 non-null  float32
dtypes: Int8(5), float32(2), int64(1), object(1), str(25)
memory usage: 11.0+ MB

In [147]:
data.sample(5)

,ID,Age,Country,Education_level,Main_Branch,Employment,Job_title,Industry,Work_exp,Years_coding,Org_size,Work_mode,Role_type,Learned_AI_tools,AI_learning_source,Salary_USD,Job_satisfaction,Languages_used,Languages_wanted,Languages_admired,Databases_used,Platforms_used,Dev_environments,AI_usage,AI_sentiment,AI_accuracy_trust,AI_handling_complex_tasks,AI_job_threat,AI_frustrations,AI_models_used,AI_agents_usage,Work_exp_clean,Years_coding_clean,Salary_clean
19654,19655,55-64,Italy,Professional/PhD,Developer,contractor/freelancer,Academic/Researcher,Software Development,25,40,Solo,Hybrid (office-leaning),Individual contributor,Yes,AI tools,NaN,8,C#;HTML/CSS;PowerShell;Python;SQL;TypeScript,C#;HTML/CSS;PowerShell;Python;SQL;TypeScript,C#;HTML/CSS;PowerShell;Python;SQL;TypeScript,MongoDB;PostgreSQL,NaN,NaN,NaN,NaN,NaN,NaN,I'm not sure,NaN,NaN,NaN,25,40,NaN
4841,4842,25-34,United Kingdom of Great Britain and Northern Ireland,Bachelor,Developer,Employed,Software Developer,Higher Education,6,7,100-499,Remote,Individual contributor,No,NaN,"66,709.00",8,TypeScript,NaN,NaN,NaN,NaN,IntelliJ IDEA,No,Unfavorable,Highly distrust,Not sure,I'm not sure,I don’t use AI tools regularly,NaN,No,6,7,"66,709.00"
43103,43104,35-44,NaN,Bachelor,Occasional coder,Employed,Other,NaN,12,28,100-499,Hybrid (office-leaning),People manager,No,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,28,NaN
17450,17451,25-34,Spain,Some college,Dev-adjacent,Employed,Infra & Security,Fintech,5,3,10000+,Remote,Individual contributor,Yes,Online resources,"43,622.00",<NA>,Ada;Bash/Shell (all shells);PowerShell;Python,Ada;Bash/Shell (all shells);Go;HTML/CSS;Java;JavaScript;Python,Ada;Bash/Shell (all shells);Python,Cosmos DB;MySQL;PostgreSQL;Snowflake,Ansible;Chocolatey;Docker,NaN,No,Unsure,Neither trust nor distrust,Good,Yes,"AI solutions that are almost right, but not quite;I’ve become less confident in my own problem-solving",NaN,No,5,3,"43,622.00"
28704,28705,65+,Belgium,Professional/PhD,Former developer,Retired,Retired,NaN,42,48,NaN,NaN,NaN,Yes,Blogs/Podcasts,NaN,<NA>,Mojo,Mojo,Mojo,NaN,NaN,Visual Studio Code,No - but want to,Indifferent,Somewhat trust,Good,NaN,"AI solutions that are almost right, but not quite;Debugging AI-generated code is more time-consuming",NaN,No - copilot only,42,48,NaN

### Finally exporting the cleaned csv dataset

In [152]:
data.to_csv('stackoverflow_survey_clean',index=False)

### NOTE --

* I kept the

In [149]:
data.sample(5)

,ID,Age,Country,Education_level,Main_Branch,Employment,Job_title,Industry,Work_exp,Years_coding,Org_size,Work_mode,Role_type,Learned_AI_tools,AI_learning_source,Salary_USD,Job_satisfaction,Languages_used,Languages_wanted,Languages_admired,Databases_used,Platforms_used,Dev_environments,AI_usage,AI_sentiment,AI_accuracy_trust,AI_handling_complex_tasks,AI_job_threat,AI_frustrations,AI_models_used,AI_agents_usage,Work_exp_clean,Years_coding_clean,Salary_clean
21564,21565,35-44,Germany,Master,Developer,Employed,Software Developer,Software Development,13,22,10000+,Remote,Individual contributor,Yes,AI tools,"197,225.00",8,Bash/Shell (all shells);C;C++;Go;Groovy;HTML/CSS;Java;JavaScript;Python;Ruby;SQL;TypeScript,NaN,NaN,PostgreSQL,Amazon Web Services (AWS);Docker;Homebrew;Make;Maven (build tool);Ninja;npm,Vim;Visual Studio Code,Yes - daily,Favorable,Somewhat distrust,Bad,No,"AI solutions that are almost right, but not quite",NaN,No - copilot only,13,22,"197,225.00"
2506,2507,55-64,United States of America,Master,Developer,Employed,Software Developer,Software Development,35,38,10000+,Remote,Individual contributor,Yes,AI tools,NaN,4,Bash/Shell (all shells);Java;PowerShell;SQL,Bash/Shell (all shells);Java;SQL,Bash/Shell (all shells);Java;SQL,Microsoft SQL Server;Oracle;PostgreSQL,NaN,IntelliJ IDEA;Notepad++,Yes - daily,Favorable,Somewhat distrust,Very poor,I'm not sure,"AI solutions that are almost right, but not quite",openAI GPT (chatbot models);openAI Reasoning models,No - but want to,35,38,NaN
2940,2941,25-34,United States of America,Bachelor,Developer,Not employed,Software Developer,NaN,5,10,NaN,NaN,NaN,No,NaN,NaN,6,C#;Java;Lua;PowerShell;Python;Rust,C#;Java;Kotlin;PowerShell;Python,C#;Java;PowerShell;Python,NaN,Docker;Gradle;Kubernetes;Maven (build tool);Microsoft Azure;NuGet,Android Studio;IntelliJ IDEA;Notepad++;RustRover;Visual Studio;Visual Studio Code;VSCodium,Yes - sometimes,Unfavorable,Highly distrust,Very poor,Yes,"AI solutions that are almost right, but not quite;Debugging AI-generated code is more time-consuming;I don’t use AI tools regularly",NaN,No,5,10,NaN
48875,48876,35-44,Germany,Master,Developer,Employed,Software Developer,Software Development,18,21,100-499,Remote,Individual contributor,Yes,AI tools,NaN,7,Bash/Shell (all shells);C#;Delphi;Groovy;HTML/CSS;Java;JavaScript;PowerShell;Python;SQL,Bash/Shell (all shells);HTML/CSS;Java;JavaScript;PowerShell;Python;SQL;TypeScript,Bash/Shell (all shells);HTML/CSS;Java;JavaScript;PowerShell;Python;SQL,Microsoft Access;Microsoft SQL Server;Oracle;PostgreSQL,Amazon Web Services (AWS);Docker;MSBuild,Sublime Text;Visual Studio Code,Yes - daily,Favorable,Somewhat distrust,Very poor,No,"AI solutions that are almost right, but not quite;It’s hard to understand how or why the code works",openAI GPT (chatbot models),Yes - weekly,18,21,NaN
8815,8816,45-54,NaN,Secondary school,Developer,contractor/freelancer,Software Developer,Software Development,31,35,<20,Flexible,Individual contributor,Yes,Other,NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,31,35,NaN